apiVersion: batch/v1
kind: CronJob
metadata:
  name: pg-backup
  namespace: payments-namespace
spec:
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pg-dump
            image: postgres:14-alpine
            envFrom:
            - secretRef:
                name: pg-secret
            command:
            - /bin/sh
            - -c
            - |
              PGPASSWORD=$POSTGRES_PASSWORD pg_dump -h postgres \
                -U $POSTGRES_USER payments_db | gzip > /backup/$(date +%F-%H%M).sql.gz
            volumeMounts:
            - name: backup-vol
              mountPath: /backup
          restartPolicy: OnFailure
          volumes:
          - name: backup-vol
            persistentVolumeClaim:
              claimName: pg-backup-pvc
