apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: payments-kafka
  namespace: payments-namespace
spec:
  kafka:
    replicas: 3
    listeners:
    - name: plain
      port: 9092
      type: internal
    config:
      offsets.topic.replication.factor: 2
      transaction.state.log.replication.factor: 2
      transaction.state.log.min.isr: 2
    storage:
      type: persistent-claim
      size: 20Gi
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 10Gi
